---

on:
    push:
        branches:
            - main
            
jobs:
    job-1:
        runs-on: ubuntu-latest
        outputs:
            artifacts: my-app
        steps:
            - name: step 1
              run: echo "tip=hello" >> $GITHUB_OUTPUT
            - name: step 2
              run: echo "output from step1 is ${{ steps.step1.outputs.tip }}"
    job-2:
        needs: job-1
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ needs.job-1.outputs.artifact }}"            
              