on:
  push:
    branches:
      - main

jobs:
  context-job:
    runs-on: ubuntu-latest
    steps:
      - name: show repo and actor
        run: echo "Repo: ${{ github.repository }} by ${{ github.actor }}"

      - name: show complete github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: show complete env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"

      - name: show complete runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
                              
